### ISSUE TITLE
pay.min.js not found (404)

### ISSUE THREAD

**Issue by baransu** [SagePayments/PaymentsJS#1]
<img width="920" alt="screen shot 2016-08-08 at 14 55 47" src="https://cloud.githubusercontent.com/assets/9558691/17487880/1e1f1922-5d97-11e6-9a47-11564d658def.png">
![screen shot 2016-08-08 at 14 55 53](https://cloud.githubusercontent.com/assets/9558691/17487875/18d49bd6-5d97-11e6-9270-eb6030447d36.png)

**Comment by majidmade** [comment]
Hi @Baransu ,

I apologize, the JavaScript library is still in the final stages of deployment on our end. I'll update you the moment that changes. Sorry for the inconvenience, and thank you for your interest!

**Comment by majidmade** [comment]
Closing issue; the JavaScript files are now available via https://www.sagepayments.net/pay/1.0.0/js/pay.min.js -- I apologize for any inconveniences.

Support and developer credentials are available via https://developer.sagepayments.com/
