### ISSUE TITLE
Doesn't work in IE9

### ISSUE THREAD

**Issue by octoxan** [SagePayments/PaymentsJS#16]
Throws 'PayJS' is undefined.

**Comment by thlinux1107** [comment]
octoxan, do you have "debug" set to true? If so, can you take a look at the console and post screenshots of the error(s)?

**Comment by thlinux1107** [comment]
octoxan, our developer was able to identify the issue. PaymentsJS uses "ECMAScript 2015" (aka "ES6") - These standards allow JavaScript consistent across browsers. Internet Explorer doesn't support ES6 until IE11. It will not work in IE9 or IE10. We have added a backlog for a future release to expand browser support that should resolve this in  older browsers such as IE9. In the meantime you may want to add a note on your site to "Please use X browser for best experience".

**Comment by majidmade** [comment]
All modules will be transpiled to ES5 in an upcoming release.
