### ISSUE TITLE
Back end question

### ISSUE THREAD

**Issue by Tlturner77** [SagePayments/PaymentsJS#25]
Does this require nodeJS? The reason for this question what obfuscates my merchant key and id from the rest of the world. When I use Sage Exchange in PHP that data is all server side.

**Comment by thlinux1107** [comment]
PaymentsJS is a JavaScript library that allows you to isolate your code from PCI data, reducing your PCI burden. You are not required to use NodeJS, however we have provided samples in NodeJS, PHP, and .Net. It will be up to you how you decide to obfuscate the Merchant Credentials (Merchant ID and Merchant Key) and your Developer Credentials (Client ID and Client Secret).

**Comment by majidmade** [comment]
Hi @Tlturner77, good question!

Before you render the page to the client, you'll create an encrypted version of your settings, which includes your `merchantKey`:

```php
<?php
    require('../shared/shared.php');
    
    $nonces = getNonces();
    $environment = $request['environment'];
    $req = [
        "merchantId" => $merchant['ID'],
        "merchantKey" => $merchant['KEY'],
        "requestType" => "payment",
        "orderNumber" => "Invoice" . rand(0, 1000),
        "amount" => $request['amount'],
        "salt" => $nonces['salt'],
        "postbackUrl" => $request['postbackUrl'],
        "preAuth" => $request['preAuth']
    ]; 
    
    $authKey = getAuthKey(json_encode($req), $developer['KEY'], $nonces['salt'], $nonces['iv']);
?>
```

Then you pass some of these values into the client library, for the browser:

```javascript
$UI.Initialize({
      clientId: "<?php echo $developer['ID']; ?>",
      postbackUrl: "<?php echo $req['postbackUrl']; ?>",
      environment: "<?php echo $environment; ?>",
      merchantId: "<?php echo $req['merchantId']; ?>",
      authKey: "<?php echo $authKey; ?>",
      salt: "<?php echo $req['salt']; ?>",
      requestType: "<?php echo $req['requestType']; ?>",
      orderNumber: "<?php echo $req['orderNumber']; ?>",
      amount: "<?php echo $req['amount']; ?>",
      preAuth: "<?php echo $req['preAuth']; ?>"
});
```
Notice that:

1. the `merchantKey` isn't one of them, and
2. the `authKey` *is* one of them.

On the back-end, PaymentsJS decrypts the `authKey` and grabs the `merchantKey` from there. The other values -- `amount`, for instance -- are checked for tampering... so if someone tried the change the `amount` from `100` to `1`, we'd see that there's a mismatch between the plaintext and encrypted versions, and throw a 401.

Check out the [PHP samples](https://github.com/SagePayments/PaymentsJS/tree/master/Samples/php) that @thlinux1107 mentioned if you'd like to play with it yourself!
