### ISSUE TITLE
Chrome Autocomplete doesn't work for credit card field

### ISSUE THREAD

**Issue by collinanderson** [SagePayments/PaymentsJS#26]
Please consider adding autocomplete="cc-number" to the credit card input field and proper autocomplete attributes to the other fields.

The fields also need to be wrapped in a &lt;form&gt; element.

More information here:
https://developers.google.com/web/fundamentals/design-and-ui/input/forms/#use_metadata_to_enable_auto-complete

https://html.spec.whatwg.org/multipage/form-control-infrastructure.html#attr-fe-autocomplete-cc-number
https://www.w3.org/TR/html/sec-forms.html#sec-autofill

**Comment by rflores76** [comment]
Hi Collin,

  For security purpose, we do not allow autocomplete. Adding a feature like this will also require an extra layer of validation, which can also be an inconvenience to some. However, we do appreciate all feedback and will be submitting your request to our Product team for review.


Please take the time out to register at our new Developer Portal<https://developer.sagepayments.com/> and take advantage of our new API: https://developer.sagepayments.com/

Robert Flores
Integration Consultant, Product Integration
Sage

Office: 1- 800-261-0240
Twitter<https://twitter.com/SageNAmerica> | YouTube<http://www.youtube.com/user/SageSoftwareNA> | LinkedIn<http://www.linkedin.com/company/2802?goback=%2Efcs_GLHD_The+Sage+Group_false_*2_*2_*2_*2_*2_*2_*2_*2_*2_*2_*2_*2&trk=ncsrch_hits> | Facebook<https://www.facebook.com/Sage> | Sage City<http://sagecity.na.sage.com/>

The information contained in this email transmission (including any document, file, or previous e-mail message within it) may constitute confidential information.  If you are not the intended recipient, or a person responsible for delivering it to the intended recipient, please take notice that any disclosure, copying, distribution, or use of any of this information is PROHIBITED.  If you receive this email in error, please immediately notify me by contacting me at the email or phone number listed above and destroy the original transmission without reading or saving it.
