### ISSUE TITLE
Customer billing and shipping address with UI

### ISSUE THREAD

**Issue by runrevben** [SagePayments/PaymentsJS#30]
Hello,

I'm trying to set the customer billing and shipping so they appear in my virtual terminal. I can see this can be done with CORE, but there doesn't appear to be a way with UI. Is this he case? UI is working great and I don't really want to have to change the code if I can avoid it.. I tried using CORE and UI in conjunction but that doesn't appear to work.. seems you have to use CORE with REQUEST.. can someone advise.

Thanks,

Ben

**Comment by thlinux1107** [comment]
Ben,

Thanks for reaching out to us. You are correct, the UI option is fairly limiting in the fields offered. You can gather the billing address data in a separate form and submit the within the `initialize()` script under a `billing` object. We are currently working on a new version of PaymentsJS that will update the flexibility of the UI including allowing the billing address to be entered, but we do not have a release date at this time. If you have any additional questions please feel free to reply here or reach out to us directly at sdksupport@paya.com.

Thomas
SDK Support
