### ISSUE TITLE
ASP.NET CORE 2.1 error 400000

### ISSUE THREAD

**Issue by KrzysztofPajak** [SagePayments/PaymentsJS#31]
Hi,
Unfortunately but in ASP.NET CORE 2.1 is not possible run integration. 
We use the same code as in sample, but always we get response from Paya: 
"code": "400000",
"message": "There was a problem with the request. Please see 'detail' for more.",
"detail": "Unable to complete request. This is usually means the authKey could not be decrypted." 
Thanks for any help.

Regards
Krzysztof

**Comment by thlinux1107** [comment]
Krzysztof,

Thanks for reaching out, I received the note at our sdksupport@paya.com address as well and have sent a reply. However, once we figure out the discrepancy we'll make sure to post the resolution here to help others with the same issue.

Thomas - SDK Support
