### ISSUE TITLE
Incompatible with other scripts that `define()` anonymous modules

### ISSUE THREAD

**Issue by ascott18** [SagePayments/PaymentsJS#32]
The hard dependency on RequireJS means that any other scripts that call `define(null, [...], function() { ... })` or `define([...], function() { ... })` will not work on pages that use PaymentsJS. The main use case here is in a WordPress site where themes are loading all sorts of scripts that are registering anonymous AMD modules.

For example, jQuery UI's position module registers an anonymous AMD module: https://github.com/jquery/jquery-ui/blob/master/ui/position.js#L22 

However, RequireJS doesn't support anonymous modules: https://requirejs.org/docs/errors.html#mismatch
> If you manually code an HTML script tag, **be sure it only includes named modules**, and that an anonymous module that will have the same name as one of the modules in that file is not loaded.

Could a version of PaymentsJS be provided that doesn't have a hard dependency on any particular module framework? For example, in the jQuery UI code linked above, an AMD module is registered if an AMD implementation is detected, but otherwise it defaults to registering browser globals. 

Or, if such a version already exists, could you point me to the documentation? 

Thanks!

**Comment by thlinux1107** [comment]
ascott18,

Thank you for the note and detailed explanation. This is the only version of PaymentsJS available at this time. I will bring this to our developers attention. We do not have a timetable for any new releases of this product but there has been interest from our clients for an updated version that at least includes ACH.

Thank you,
Thomas H - SDK Support
