### ISSUE TITLE
CORS Issue

### ISSUE THREAD

**Issue by bartboy011** [SagePayments/PaymentsJS#8]
As the issue title says, I'm having issues with the ajax request response being blocked (in Chrome, haven't tested other browsers). 

![screen shot 2016-09-19 at 12 08 23 pm](https://cloud.githubusercontent.com/assets/20690809/18641544/c19d2da0-7e62-11e6-89dd-7c3f56c3f89b.png)

Some specs:

This is being added to a Rails webstore. Currently in dev and hosted locally. Here's the code:

```
<%
cipher = OpenSSL::Cipher::AES.new(256, :CBC)
cipher.encrypt

iv = OpenSSL::Random.pseudo_bytes(16)
salt = Base64.strict_encode64(iv) 
req = [
    "apiKey" => ENV['sage_api_key'],
    "merchantId" => ENV['sage_merchant_id'],
    "merchantKey" => ENV['sage_merchant_key'],
    "requestType" => "payment",
    "requestId" => "Invoice12345",
    "postbackUrl" => "https://www.example.com/",
    "amount" => "1.00",
    "nonce" => salt,
    "preAuth" => false
] 
data = JSON.generate(req)
password = ENV['sage_secret_key']
key = OpenSSL::PKCS5.pbkdf2_hmac_sha1(password, salt, 1500, 32)
cipher.key = key
cipher.iv  = iv
authKey = cipher.update(data) + cipher.final()
authKey = Base64.strict_encode64(authKey)
%>

<script>
PayJS(['PayJS/UI'], // the name of the module we want to use
    function($UI) { // assigning the module to a variable
        $UI.Initialize({ // configuring the UI
            apiKey: <%= ENV['sage_api_key'] %>, // your developer ID
            merchantId: "<%= ENV['sage_merchant_id'] %>",
            authKey: "<%= authKey %>", // covered in the next section!
            requestType: "payment", // use can use "vault" to tokenize a card without charging it
            requestId: "Invoice12345", // an order number, customer or account identifier, etc.
            amount: "1.00", // the amount to charge the card. in test mode, different amounts produce different results.
            elementId: "paymentButton", // the page element that will trigger the UI
            nonce: "<%= salt %>", // a unique identifier, used as salt
            debug: true, // enables verbose console logging
            preAuth: false, // run a Sale, rather than a PreAuth
            environment: "cert", // hit the certification environment
            addFakeData: true
        });
        $UI.setCallback(function(result) { // custom code that will execute when the UI receives a response
            console.log(result.getResponse()); // log the result to the console
            var wasApproved = result.getTransactionSuccess();
            alert(wasApproved ? "ka-ching!" : "bummer");
        });
    }
);
</script>
```

Thoughts?

**Comment by thlinux1107** [comment]
Thanks for contacting us, we're happy to reach out and help. It looks like there may be an issue with AJAX and Cross-Origin HTTP requests. I am currently on the road and will not have full access to take a look at your code until this evening. In the meantime I found an article that may apply and help. Please take a look at https://developer.mozilla.org/en-US/docs/Web/HTTP/Access_control_CORS. If you find that helps please let me know. Otherwise I will let you know what I find later this evening. 

Also, please feel free to submit issues through GitHub, the developer portal at developer.sagepayments.com, or through our email address at sdksupport@sage.com

**Comment by majidmade** [comment]
Hey guys,

It's possible the CORS error is a red herring, here, and there is a mismatch between the "expected request" (ie, the one that's encrypted server-side) and the "actual request" (the one that's initialized and sent client-side).

Joshua, if you could please try:
1. Add `environment => "cert"` to the encrypted payload, server-side.
2. Add `postbackUrl: "https://www.example.com/"` to the initialization method, client-side.

I think those may be the culprits. There may also be an error message in the response with more detail, which you can see from the "Network" tab of Chrome's dev console.

Please let me know if these help; if they do, then the defects are that:

(a) The API doesn't return the appopriate CORS headers when the expected/actual requests do not match.
(b) The sample code does not denote a valid request and needs to be updated accordingly.

Of course, if these suggestions _don't_ help, then we'll work with you until we figure it out. In either case, I apologize for the inconvenience.

Thanks,
Majid

**Comment by bartboy011** [comment]
Hey guys,

Thanks for the suggestions. @thlinux1107, this article is definitely helpful, but would, I'm pretty sure at least, only be implementable on your side of things. 

@majidmade, I've added your suggestions and am still getting the same error. Here's the updated (and cleaned up for readibility) code:

```
<%
cipher = OpenSSL::Cipher::AES.new(256, :CBC)
cipher.encrypt

iv   = OpenSSL::Random.pseudo_bytes(16)
salt = Base64.strict_encode64(iv) 
req  = [
    "apiKey"      => ENV['sage_api_key'],
    "merchantId"  => ENV['sage_merchant_id'],
    "merchantKey" => ENV['sage_merchant_key'],
    "requestType" => "payment",
    "requestId"   => "Invoice12345",
    "postbackUrl" => "https://www.example.com/",
    "amount"      => "1.00",
    "nonce"       => salt,
    "preAuth"     => false,
    "environment" => "cert"
] 
data          = JSON.generate(req)
password  = ENV['sage_secret_key']
key            = OpenSSL::PKCS5.pbkdf2_hmac_sha1(password, salt, 1500, 32)
cipher.key = key
cipher.iv    = iv
authKey     = cipher.update(data) + cipher.final()
authKey     = Base64.strict_encode64(authKey)
%>

<script>
PayJS(['PayJS/UI'], // the name of the module we want to use
    function($UI) { // assigning the module to a variable
        $UI.Initialize({ // configuring the UI
            apiKey:      "<%= ENV['sage_api_key'] %>",
            merchantId:  "<%= ENV['sage_merchant_id'] %>",
            authKey:     "<%= authKey %>",
            requestType: "payment",
            requestId:   "Invoice12345",
            amount:      "1.00",
            elementId:   "paymentButton",
            nonce:       "<%= salt %>",
            debug:       true,
            preAuth:     false,
            environment: "cert",
            addFakeData: true,
            postbackUrl: "https://www.example.com/"
        });
        $UI.setCallback(function(result) { 
            console.log(result.getResponse());
            var wasApproved = result.getTransactionSuccess();
            alert(wasApproved ? "ka-ching!" : "bummer");
        });
    }
);
</script>
```

And a screenshot of the full console, rather than just the small snippet I included before:
![screen shot 2016-09-19 at 2 10 48 pm](https://cloud.githubusercontent.com/assets/20690809/18645457/e6513bf4-7e72-11e6-8583-ea946a32669c.png)

I'm not sure why the merchantId isn't being found, I pulled it straight from our Merchant account page, but that is probably not relevant here (I added it in the latest round of testing, after the initial issue was posted).

**Comment by majidmade** [comment]
Hmm, strange. Does the Response value in that logged object (third line from the bottom in that latest screenshot) have a message inside? I'm also starting a trace session server-side to get more data.

**Comment by bartboy011** [comment]
Yeah, it does. Here's the first level of it opened, let me know if you want more:

![screen shot 2016-09-19 at 2 30 04 pm](https://cloud.githubusercontent.com/assets/20690809/18646091/a5d4a8e2-7e75-11e6-9a61-e61a7c0d8637.png)

**Comment by majidmade** [comment]
I saw a couple of requests come through the trace session; this is helpful, thanks! Looks like the server is getting a "Malformed UTF-8 data" during the decryption of the authKey, so we can narrow the problem down to that.

I don't have much (any) experience with Ruby, but I encountered something similar when working on a [PaymentsJS sample in C#](https://github.com/SagePayments/PaymentsJS/blob/master/Samples/dotnet/shared/Shared.cs) -- before converting the IV to a Base64 string for the salt, I had to first convert it to a hex string, and then a UTF-8 array, and _then_ a base64 string.

**Comment by bartboy011** [comment]
If you still have that trace session open, I've run a few more requests through, none of which have worked unfortunately. I've tried a few different methods of that conversion method, and all seem to produce the same results, but none are successful in the end, unfortunately. Here are the steps:

```
iv   = OpenSSL::Random.pseudo_bytes(16)     #create a random byte string
iv   = iv.each_byte.map { |byte| byte.to_s(16) }.join    #convert it to hex string
iv   = iv.bytes.to_a          #convert hex string to byte array
iv   = iv.pack('U*')          #convert byte array to UTF-8 string
salt = Base64.strict_encode64(iv)      #base64 encode UTF-8 string
```

Here's the progressive result of that, if it helps:

```
"\x0FZA\xE4\xB7a\xF9;\x93d\xB65$V\x84P"    #bytes
"f5a41e4b761f93b9364b63524568450"          #hex string
[102, 53, 97, 52, 49, 101, 52, 98, 55, 54, 49, 102, 57, 51, 98, 57, 51, 54, 52, 98, 54, 51, 53, 50, 52, 53, 54, 56, 52, 53, 48]     #byte array
"f5a41e4b761f93b9364b63524568450"         #back to string (UTF-8)
"ZjVhNDFlNGI3NjFmOTNiOTM2NGI2MzUyNDU2ODQ1MA==" #encode as Base64
```

Ruby doesn't seem to be particularly suited for this endeavor...

Edit: removed the unnecessary "p iv" after each line (for logging purposes).

Edit 2: Here's the authKey after Base64 encoding as well (sensitive data has been removed and default values restored in the req array):

```
"UEj02fQgYKyCl7ie70eakd4kNtLS8YChh6hltDEd5XcB2psqvtEKtMVhCBjOVkDHNNzfe8JrAOieF6LVRnrCFZog5iyNW7/wsLJ8yfCi730/vWeM+mRlSThX4nTJoPIQ3WMTfBEFmOnfZVnISSehuLMfjhIwQSbA6G5tLm6M4K8HXZ5L9TYtrLHgj/iilxvqdzgGLgAEKKDIlUB+T3I1LWg2LT02leC4p2dEj0MJvUoat+iPUPY5CQdF5KiQ6o9q9NveRljIq7/ksfRSDcLzHfGMJaQA1LXvjNFBVAjvRQ0dWxWbBoCsAUk/1ebmI75jGlPS6ve4FTFHLD05neZeSrAKbYWspWlOOP1TfdQxPFYzGpxrhc0uj6+HtMBNhRlaTAlEKeZEjY8rtU2xG27zgQ=="
```

**Comment by majidmade** [comment]
The sample code was really useful, thanks! I was able to scrounge together a VM with RoR, which let me hit our dev environment and gather more data. I think I have the solution for you -- just need a few minutes to test it out in the cert environment. Appreciate your patience!

**Comment by bartboy011** [comment]
Awesome, thank you!

**Comment by majidmade** [comment]
Okay, this is working! Sweet.

So, there were three things that I changed for the encryption.

First thing was changing the variable names from `iv` to `salt` -- the original IV was good, it was just the salt that was the challenge.

The second was to change how we get the hex string. I won't pretend to understand _exactly_ what the difference is, but it was something to do with the length of the string not being consistent between attempts:

``` ruby
iv   = OpenSSL::Random.pseudo_bytes(16)
#thing one: changed these variable names from 'iv' to 'salt'
salt = iv.unpack('H*').first #thing two: changed this line
salt   = salt.bytes.to_a
salt   = salt.pack('U*')
salt = Base64.strict_encode64(salt)
```

Final thing for the encryption was to change `req` from an array to a hash. I don't know how they differ Ruby-wise but it seemed to make a difference on the JSON end:

``` ruby
req  = {
    "apiKey"      => apikey,
    "merchantId"  => mid,
    "merchantKey" => mkey,
    "requestType" => "payment",
    "requestId"   => reqid,
    "postbackUrl" => "https://www.example.com/",
    "amount"      => "1.00",
    "nonce"       => salt,
    "preAuth"     => false,
    "environment" => "cert"
}
```

There were two other random things that would have been an issue after the encryption, so I took care of those too.

Duplicate `requestId` values result in `DUPLICATE TRANS` rejections, so I made that dynamic:

``` ruby
reqid = "invoice" + rand(10...42).to_s
```

There's a bug in the current version that rejects transactions if they don't contain billing data. This'll be fixed in the next release (which will be soon), but in the meantime setting dummy data does the trick:

``` javascript
$UI.Initialize({ // configuring the UI
            apiKey:      "<%= apikey %>",
            merchantId:  "<%= mid %>",
            authKey:     "<%= authKey %>",
            requestType: "payment",
            requestId:   "<%= reqid %>",
            amount:      "1.00",
            elementId:   "paymentButton",
            nonce:       "<%= salt %>",
            preAuth:     false,
            environment: "cert",
            postbackUrl: "https://www.example.com/",
            addFakeData: true,
            debug: true,
            show: true,
            billing: {
                name: "Shaka Smart",
                address: "",
                city: "Denver",
                state: "CO",
                postalCode: "80205"
            }
        });
```

**Comment by majidmade** [comment]
Here's the full source code (I hard-coded some test credentials in):

``` ruby```
<%
cipher = OpenSSL::Cipher::AES.new(256, :CBC)
cipher.encrypt

iv   = OpenSSL::Random.pseudo_bytes(16)
salt = iv.unpack('H*').first
salt   = salt.bytes.to_a
salt   = salt.pack('U*')
salt = Base64.strict_encode64(salt)

mid = "999999999997";
mkey = "K3QD6YWyhfD";
apikey = "7SMmEF02WyC7H5TSdG1KssOQlwOOCagb";
apisecret = "wtC5Ns0jbtiNA8sP";

reqid = "invoice" + rand(10...42).to_s

req  = {
    "apiKey"      => apikey,
    "merchantId"  => mid,
    "merchantKey" => mkey,
    "requestType" => "payment",
    "requestId"   => reqid,
    "postbackUrl" => "https://www.example.com/",
    "amount"      => "1.00",
    "nonce"       => salt,
    "preAuth"     => false,
    "environment" => "cert"
}

data          = JSON.generate(req)
key            = OpenSSL::PKCS5.pbkdf2_hmac_sha1(apisecret, salt, 1500, 32)
cipher.key = key
cipher.iv    = iv
authKey     = cipher.update(data) + cipher.final()
authKey     = Base64.strict_encode64(authKey)
%>
<script type="text/javascript" src="https://www.sagepayments.net/pay/1.0.0/js/pay.min.js"></script>

<script>
PayJS(['PayJS/UI'], // the name of the module we want to use
    function($UI) { // assigning the module to a variable
        $UI.Initialize({ // configuring the UI
            apiKey:      "<%= apikey %>",
            merchantId:  "<%= mid %>",
            authKey:     "<%= authKey %>",
            requestType: "payment",
            requestId:   "<%= reqid %>",
            amount:      "1.00",
            elementId:   "paymentButton",
            nonce:       "<%= salt %>",
            preAuth:     false,
            environment: "cert",
            postbackUrl: "https://www.example.com/",
            addFakeData: true,
            debug: true,
            show: true,
            billing: {
                name: "Shaka Smart",
                address: "",
                city: "Denver",
                state: "CO",
                postalCode: "80205"
            }
        });
        $UI.setCallback(function(result) { 
            console.log(result.getResponse());
            var wasApproved = result.getTransactionSuccess();
            //alert(wasApproved ? "ka-ching!" : "bummer");
        });
    }
);
</script>
<button id="paymentButton">PAY</button>
```

**Comment by majidmade** [comment]
Please let me know how that goes!

Action items _(cc: @thlinux1107, @jsmutz, @rflores76):_
1. Create a Ruby sample and add it alongside the .NET and PHP samples in this repository.
2. Log defect: CORS headers are not sent on failed transactions.

**Comment by bartboy011** [comment]
Unfortunately, I'm still getting a CORS error. However, while I was at home last night and unable to test this fix, I made a ruby gem out of all of this to make the process a little cleaner. [Here's the link to it.](https://github.com/bartboy011/paymentsjs-rails)

**Comment by bartboy011** [comment]
Here's the js that's being sent over:
![screen shot 2016-09-20 at 9 04 56 am](https://cloud.githubusercontent.com/assets/20690809/18673445/724c7986-7f11-11e6-9f3e-96833ff0d163.png)
And here's the console log:
![screen shot 2016-09-20 at 9 06 28 am](https://cloud.githubusercontent.com/assets/20690809/18673478/906562a2-7f11-11e6-9452-ae6cf5587337.png)

You'll notice that the merchant id is recognized, so there's something.

**Comment by bartboy011** [comment]
For sake of testing, I went back and used just the code you posted above, and it works perfectly. So, the issue is now somewhere in the gem!

**Comment by bartboy011** [comment]
Found the bug, everything is working! Thank you so much for the help guys, I really appreciate it.

Edit: It appears to be back. I'm going to keep taking a look at this gem and see if I can figure it out.

**Comment by majidmade** [comment]
Really appreciate you taking the time to turn this into a ruby gem for the community! Let me know if you need help troubleshooting; I know the server-side aspect is pretty opaque on your end..

**Comment by bartboy011** [comment]
Absolutely. Currently testing it out now. I've started getting a 401 Unauthorized response from Sage, that's intentional, yes?

**Comment by majidmade** [comment]
Yeah -- 401 means there was a mismatch between the expected request (the decrypted authKey) and the actual request.

**Comment by bartboy011** [comment]
Everything seems to be in working order finally. I'll do a new readme on the gem page since it's outdated now and with that, I believe this issue can be closed. Thanks again for the help!

**Comment by majidmade** [comment]
Happy to help! Thanks again for creating the gem. If it's okay with you, I'll link to it somewhere in this repo.

**Comment by bartboy011** [comment]
That would be great! Thanks!
